### ISSUE TITLE
OSError: [Errno 63] File name too long

### ISSUE THREAD

**Issue by gianpaj** [0xpayne/gpt-migrate#13]
<details><summary>vue.js 1 to 3</summary>
<p>

```
$ python main.py --sourcelang "vue.js 1"  --targetlang "vue.js 3" --sourcedir ../benchmarks/vue1-vue3 --sourceentry "index.html" --model "gpt-3.5-turbo-16k"
◐ Reading vue.js 1 project from directory '/Users/user/gpt-migrate/benchmarks/vue1-vue3', with entrypoint 'index.html'.
◑ Outputting vue.js 3 project to directory '/Users/user/gpt-migrate/benchmarks/flask-nodejs/target'.
Source directory structure:

        ├── favicon-16x16.png
        ├── safari-pinned-tab.svg
        ├── favicon.ico
        ├── index.html
        ├── android-chrome-192x192.png
        ├── apple-touch-icon.png
        ├── renovate.json
        ├── css/
            │   └── all.css
        ├── js/
            │   └── all.js
        ├── 404.html
        ├── README.md
        ├── img/
            │   ├── walnut-logo.svg
            │   ├── walnut-logo-white-background.png
            │   ├── spin.svg
            │   ├── share.svg
            │   └── walnut-logo-white-background view.svg
        ├── channels.js
        ├── android-chrome-512x512.png
        ├── site.webmanifest
        ├── package-lock.json
        ├── package.json
        ├── scripts/
            │   └── check-channels.js
        ├── mstile-150x150.png
        ├── browserconfig.xml
        └── favicon-32x32.png

✅  Creating your environment...
Created Docker environment for vue.js 3 project in directory '/Users/user/gpt-migrate/benchmarks/flask-nodejs/target'.
✅  Identifying external dependencies for index.html...
✅  Identifying internal dependencies for index.html...
✅  Creating migration file for index.html...
Created file_name.ext at /Users/user/gpt-migrate/benchmarks/flask-nodejs/target
Copied renovate.json from /Users/user/gpt-migrate/benchmarks/vue1-vue3 to /Users/gianpaj/tmp/gpt-migrate/benchmarks/flask-nodejs/target
✅  Creating dependencies file required for the Docker environment...
Traceback (most recent call last):
```

</p>
</details>

```
  File "/Users/user//gpt-migrate/gpt_migrate/main.py", line 100, in main
    add_env_files(globals)

  File "/Users/user/gpt-migrate/gpt_migrate/steps/migrate.py", line 91, in add_env_files
    external_deps_name, _, external_deps_content = llm_write_file(prompt,
                                                   ^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/user/gpt-migrate/gpt_migrate/utils.py", line 61, in llm_write_file
    with open(os.path.join(globals.targetdir, file_name), 'w') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

OSError: [Errno 63] File name too long: "/Users/user/gpt-migrate/benchmarks/flask-nodejs/target/PREFERENCE LEVEL 1\n\nHere are the guidelines for this prompt:\n\n1. Follow the output instructions precisely and do not make any assumptions. Your output will not be read by a human; it will be directly input into a computer for literal processing. Adding anything else or deviating from the instructions w
```

**Comment by 0xpayne** [comment]
Have you made any changes to your version? If not, mind sharing the source repo you're working with?

**Comment by gianpaj** [comment]
I didn't make any changes to `gpt-migrate` 

The repo is https://github.com/gianpaj/walnut.tv

**Comment by JobberRT** [comment]
same here, using a single minified js file as source and golang as target.

**Comment by mahmoud** [comment]
Ran into this as well. Details:

* Angular 1 -> SvelteKit
* Repo: https://github.com/hatnote/montage
* CLI command: `python -m pdb ../gpt_migrate/main.py --sourcedir ~/hatnote/montage/client --sourcelang angular --targetlang sveltekit --targetdir ../workspace/ --sourceentry src/app.module.js --model gpt-3.5-turbo-16k` (`-m pdb` for CLI debugging)

For some reason, `response` in `ai.AI.write_code` is apparently a regurgitation of the prompt.

```
<OpenAIObject chat.completion id=chatcmpl-7Zn70W4WnNH76XrAifkq4A4tCI5ch at 0x7f313d968d10> JSON: {
  "id": "chatcmpl-7Zn70W4WnNH76XrAifkq4A4tCI5ch",
  "object": "chat.completion",
  "created": 1688764622,
  "model": "gpt-3.5-turbo-16k-0613",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "PREFERENCE LEVEL 1\n\nHere are the guidelines for this prompt:\n\n1. Follow the output instructions precisely and do not make any assumptions. Your output will not be read by a human; it will be directly input into a computer for literal processing. Adding anything else or deviating from the instructions will cause the output to fail.\n2. Think through the answer to each prompt step by step to ensure that the output is perfect; there is no room for error.\n3. Do not use any libraries, frameworks, or projects that are not well-known and well-documented, unless they are explicitly mentioned in the instructions or in the prompt.\n4. In general, use comments in code only sparingly.\n\nPREFERENCE LEVEL 2\n\nYou are a pragmatic principal engineer at Google. You are about to get instructions for code to write. This code must be as simple and easy to understand, while still fully expressing the functionality required. Please note that the code should be complete and fully functional. No placeholders. However, only write what you are asked to write. For instance, if you're asked to write a function, only write the function; DO NOT include import statements. We will do those separately.\n\nPlease strictly follow this styling guideline with no deviations. Variables will always be snake_case; either capital or lowercase. Functions will always be camelCase. Classes will always be PascalCase. Please follow this guideline even if the source code does not follow it.\n\nFinally, please follow these guidelines:\n\nPREFERENCE LEVEL 3\n\nYou are a principal software engineer at Google with particular expertise in Docker environments. Consider the below Dockerfile and create a file for external dependencies. Some languages require a specific directory and/or file name, and to address this in the file for external dependencies. The current directory structure is as follows:\n\n```\n        \u251c\u2500\u2500 Dockerfile\n        \u251c\u2500\u2500 file_name.ext\n        \u2514\u2500\u2500 src/\n                \u2514\u2500\u2500 text/\n                        \u251c\u2500\u2500 en.json\n                        \u2514\u2500\u2500 pl.json\n\n```\n\nIf this will be an issue for sveltekit, please handle for this in the external dependencies file.\n\nDockerfile:\n\n```\nCODE\n```\n\nExternal dependencies:\n\n```\nchart.js\ninfinite-scroll\npascalprecht.translate\nngMaterial\nui.router\nangular-sortable-view\n\n```\n\nPREFERENCE LEVEL 4\n\nWe will be using the output you provide as-is to create new files, so please be precise and do not include any other text. Your output needs to be ONE file; if your output contains multiple files, it will break the system. Your output should consist ONLY of the file name, language, and code, in the following format:\n\nfile_name.ext\n```language\nCODE\n```"
      },
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 644,
    "completion_tokens": 547,
    "total_tokens": 1191
  }
}
```

When I re-ran with a (more-common) target of React, I got the same result.

**Comment by Sineos** [comment]
Seeing the same with model gpt-3.5-turbo-16k on a small Python to Nodejs migration.

**Comment by carstarai** [comment]
same issue here. I am using gpt-3,5-turbo-16k too. Any resolution yet?

**Comment by MkuuWaUjinga** [comment]
I'd advise to switch to GPT-4 if possible. Gpt-3.5-turbo is much weaker at programming (see #18)

**Comment by brunolippi** [comment]
GPT-4 is not publicly available for everyone yet, is there another model more suited than gpt-3.5-turbo or any way of fixing this error?

**Comment by gianpaj** [comment]
> GPT-4 is not publicly available for everyone yet, is there another model more suited than gpt-3.5-turbo or any way of fixing this error?

 GPT-4 is available to all via the API

https://openai.com/blog/gpt-4-api-general-availability

**Comment by Sineos** [comment]
> GPT-4 is available to all via the API

Unfortunately not. Apparently only if you had a paid subscription with at least one billing beforehand. They announced a "general" availability somwhen in August

**Comment by gianpaj** [comment]
@Sineos the GPT-4 via the API is available to everyone. You _have_ to pay to use the API

I think you're referring to GPT-4 via the ChatGPT website (chat.openai.com). The API docs are here
https://platform.openai.com/docs/api-reference/chat/create

**Comment by gianpaj** [comment]
That's strange. Sorry about that. I assumed the blog post said it was available to all :(

**Comment by ivishalanand** [comment]
I am getting the same with model gpt-3.5-turbo-16k on a small Python to Nodejs migration.

**Comment by MaurerKrisztian** [comment]
I'm experiencing the same issue with different error code (OSError: [Errno 36] File name too long). I wanted to give it a shot, but I encounter this error with every project. Here's an example:

OS: Ubuntu 22.04 LTS

e.g. project: https://github.com/MaurerKrisztian/Amazon_Book_Scraper

command:
```
➜  gpt_migrate git:(main) ✗ python main.py --sourcedir ../book-scraper --sourcelang nodejs --targetlang deno --targetdir migrate-out-scraper --model gpt-3.5-turbo-16k
Unable to find the entrypoint file. Please enter it manually. This must be a file relative to the source directory.: app.ts

```

error:
```
OSError: [Errno 36] File name too long: "gpt-migrate/gpt_migrate/migrate-out-scraper/PREFERENCE LEVEL 1\n\nHere are the guidelines for this prompt:\n\n1. Follow the output instructions precisely and do not make any assumptions. Your output will not be read by a human; it 
will be directly input into a computer for literal processing. Adding anything else or deviating from the instructions will cause the output to fail.\n2. Think through the answer to each prompt step by step to ensure that the output is perfect; there is no room for error.\n3. Do not use any libraries, 
frameworks, or projects that are not well-known and well-documented, unless they are explicitly mentioned in the instructions or in the prompt.\n4. In general, use comments in code only sparingly.\n\nPREFERENCE LEVEL 2\n\nYou are a pragmatic principal engineer at Google. You are about to get 
instructions for code to write. This code must be as simple and easy to understand, while still fully expressing the functionality required. Please note that the code should be complete and fully functional. No placeholders. However, only write what you are asked to write. For instance, if you're asked
to write a function, only write the function; DO NOT include import statements. We will do those separately.\n\nPlease strictly follow this styling guideline with no deviations. Variables will always be snake_case; either capital or lowercase. Functions will always be camelCase. Classes will always be 
PascalCase. Please follow this guideline even if the source code does not follow it.\n\nFinally, please follow these guidelines:\n\nPREFERENCE LEVEL 3\n\nYou are a principal software engineer at Google with particular expertise in Docker environments. Consider the below Dockerfile and create a file for
external dependencies. Some languages require a specific directory and/or file name, and to address this in the file for external dependencies. The current directory structure is as follows:\n"

```

**Comment by Silvio-evasys** [comment]
Same here. 
Is there a solution for this issue?
